sylius_shop_api_country_show_all:
    path: /countries
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.country.show_countries_action

sylius_shop_api_country_show_provinces:
    path: /countries/{code}/provinces
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.country.show_country_provinces_action
    requirements:
        code: .+
