<?php

declare(strict_types=1);

namespace Sylius\ShopApiPlugin\Request;

use Ramsey\Uuid\Uuid;
use Sylius\ShopApiPlugin\Command\PickupCart;
use Symfony\Component\HttpFoundation\Request;

class PickupCartRequest implements CommandRequestInterface
{
    /** @var string */
    protected $token;

    /** @var string */
    protected $channel;

    public function populateData(Request $request): void
    {
        if ($request->attributes->has('token')) {
            @trigger_error('Passing pre-generated cart token for cart pickup is deprecated. Please rely on the autogenerated token.', \E_USER_DEPRECATED);
        }

        $this->token = $request->attributes->get('token', Uuid::uuid4()->toString());
        $this->channel = $request->attributes->get('channelCode');
    }

    public function getCommand(): object
    {
        return new PickupCart($this->token, $this->channel);
    }
}
